// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: C10000Msg.proto

package com.cp.im.proto.c10000msg;

public final class C10000 {
  private C10000() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface C100001c2sOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required int32 identity = 1;
    /**
     * <code>required int32 identity = 1;</code>
     *
     * <pre>
     * 用户身份 【0 普通用户 1 客服用户】
     * </pre>
     */
    boolean hasIdentity();
    /**
     * <code>required int32 identity = 1;</code>
     *
     * <pre>
     * 用户身份 【0 普通用户 1 客服用户】
     * </pre>
     */
    int getIdentity();

    // required string deviceId = 2;
    /**
     * <code>required string deviceId = 2;</code>
     *
     * <pre>
     * 设备唯一标识
     * </pre>
     */
    boolean hasDeviceId();
    /**
     * <code>required string deviceId = 2;</code>
     *
     * <pre>
     * 设备唯一标识
     * </pre>
     */
    java.lang.String getDeviceId();
    /**
     * <code>required string deviceId = 2;</code>
     *
     * <pre>
     * 设备唯一标识
     * </pre>
     */
    com.google.protobuf.ByteString
        getDeviceIdBytes();

    // required string token = 3;
    /**
     * <code>required string token = 3;</code>
     *
     * <pre>
     * 令牌
     * </pre>
     */
    boolean hasToken();
    /**
     * <code>required string token = 3;</code>
     *
     * <pre>
     * 令牌
     * </pre>
     */
    java.lang.String getToken();
    /**
     * <code>required string token = 3;</code>
     *
     * <pre>
     * 令牌
     * </pre>
     */
    com.google.protobuf.ByteString
        getTokenBytes();
  }
  /**
   * Protobuf type {@code Platform.ModelC10000.C100001c2s}
   *
   * <pre>
   * 登录
   * </pre>
   */
  public static final class C100001c2s extends
      com.google.protobuf.GeneratedMessage
      implements C100001c2sOrBuilder {
    // Use C100001c2s.newBuilder() to construct.
    private C100001c2s(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private C100001c2s(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final C100001c2s defaultInstance;
    public static C100001c2s getDefaultInstance() {
      return defaultInstance;
    }

    public C100001c2s getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private C100001c2s(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              identity_ = input.readInt32();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              deviceId_ = input.readBytes();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              token_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.cp.im.proto.c10000msg.C10000.internal_static_Platform_ModelC10000_C100001c2s_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.cp.im.proto.c10000msg.C10000.internal_static_Platform_ModelC10000_C100001c2s_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.cp.im.proto.c10000msg.C10000.C100001c2s.class, com.cp.im.proto.c10000msg.C10000.C100001c2s.Builder.class);
    }

    public static com.google.protobuf.Parser<C100001c2s> PARSER =
        new com.google.protobuf.AbstractParser<C100001c2s>() {
      public C100001c2s parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new C100001c2s(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<C100001c2s> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required int32 identity = 1;
    public static final int IDENTITY_FIELD_NUMBER = 1;
    private int identity_;
    /**
     * <code>required int32 identity = 1;</code>
     *
     * <pre>
     * 用户身份 【0 普通用户 1 客服用户】
     * </pre>
     */
    public boolean hasIdentity() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 identity = 1;</code>
     *
     * <pre>
     * 用户身份 【0 普通用户 1 客服用户】
     * </pre>
     */
    public int getIdentity() {
      return identity_;
    }

    // required string deviceId = 2;
    public static final int DEVICEID_FIELD_NUMBER = 2;
    private java.lang.Object deviceId_;
    /**
     * <code>required string deviceId = 2;</code>
     *
     * <pre>
     * 设备唯一标识
     * </pre>
     */
    public boolean hasDeviceId() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string deviceId = 2;</code>
     *
     * <pre>
     * 设备唯一标识
     * </pre>
     */
    public java.lang.String getDeviceId() {
      java.lang.Object ref = deviceId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          deviceId_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string deviceId = 2;</code>
     *
     * <pre>
     * 设备唯一标识
     * </pre>
     */
    public com.google.protobuf.ByteString
        getDeviceIdBytes() {
      java.lang.Object ref = deviceId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        deviceId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required string token = 3;
    public static final int TOKEN_FIELD_NUMBER = 3;
    private java.lang.Object token_;
    /**
     * <code>required string token = 3;</code>
     *
     * <pre>
     * 令牌
     * </pre>
     */
    public boolean hasToken() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required string token = 3;</code>
     *
     * <pre>
     * 令牌
     * </pre>
     */
    public java.lang.String getToken() {
      java.lang.Object ref = token_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          token_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string token = 3;</code>
     *
     * <pre>
     * 令牌
     * </pre>
     */
    public com.google.protobuf.ByteString
        getTokenBytes() {
      java.lang.Object ref = token_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        token_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      identity_ = 0;
      deviceId_ = "";
      token_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasIdentity()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasDeviceId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasToken()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, identity_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getDeviceIdBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getTokenBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, identity_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getDeviceIdBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getTokenBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.cp.im.proto.c10000msg.C10000.C100001c2s parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.cp.im.proto.c10000msg.C10000.C100001c2s parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.cp.im.proto.c10000msg.C10000.C100001c2s parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.cp.im.proto.c10000msg.C10000.C100001c2s parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.cp.im.proto.c10000msg.C10000.C100001c2s parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.cp.im.proto.c10000msg.C10000.C100001c2s parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.cp.im.proto.c10000msg.C10000.C100001c2s parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.cp.im.proto.c10000msg.C10000.C100001c2s parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.cp.im.proto.c10000msg.C10000.C100001c2s parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.cp.im.proto.c10000msg.C10000.C100001c2s parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.cp.im.proto.c10000msg.C10000.C100001c2s prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Platform.ModelC10000.C100001c2s}
     *
     * <pre>
     * 登录
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.cp.im.proto.c10000msg.C10000.C100001c2sOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.cp.im.proto.c10000msg.C10000.internal_static_Platform_ModelC10000_C100001c2s_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.cp.im.proto.c10000msg.C10000.internal_static_Platform_ModelC10000_C100001c2s_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.cp.im.proto.c10000msg.C10000.C100001c2s.class, com.cp.im.proto.c10000msg.C10000.C100001c2s.Builder.class);
      }

      // Construct using com.cp.im.proto.c10000msg.C10000.C100001c2s.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        identity_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        deviceId_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        token_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.cp.im.proto.c10000msg.C10000.internal_static_Platform_ModelC10000_C100001c2s_descriptor;
      }

      public com.cp.im.proto.c10000msg.C10000.C100001c2s getDefaultInstanceForType() {
        return com.cp.im.proto.c10000msg.C10000.C100001c2s.getDefaultInstance();
      }

      public com.cp.im.proto.c10000msg.C10000.C100001c2s build() {
        com.cp.im.proto.c10000msg.C10000.C100001c2s result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.cp.im.proto.c10000msg.C10000.C100001c2s buildPartial() {
        com.cp.im.proto.c10000msg.C10000.C100001c2s result = new com.cp.im.proto.c10000msg.C10000.C100001c2s(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.identity_ = identity_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.deviceId_ = deviceId_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.token_ = token_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.cp.im.proto.c10000msg.C10000.C100001c2s) {
          return mergeFrom((com.cp.im.proto.c10000msg.C10000.C100001c2s)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.cp.im.proto.c10000msg.C10000.C100001c2s other) {
        if (other == com.cp.im.proto.c10000msg.C10000.C100001c2s.getDefaultInstance()) return this;
        if (other.hasIdentity()) {
          setIdentity(other.getIdentity());
        }
        if (other.hasDeviceId()) {
          bitField0_ |= 0x00000002;
          deviceId_ = other.deviceId_;
          onChanged();
        }
        if (other.hasToken()) {
          bitField0_ |= 0x00000004;
          token_ = other.token_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasIdentity()) {
          
          return false;
        }
        if (!hasDeviceId()) {
          
          return false;
        }
        if (!hasToken()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.cp.im.proto.c10000msg.C10000.C100001c2s parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.cp.im.proto.c10000msg.C10000.C100001c2s) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required int32 identity = 1;
      private int identity_ ;
      /**
       * <code>required int32 identity = 1;</code>
       *
       * <pre>
       * 用户身份 【0 普通用户 1 客服用户】
       * </pre>
       */
      public boolean hasIdentity() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 identity = 1;</code>
       *
       * <pre>
       * 用户身份 【0 普通用户 1 客服用户】
       * </pre>
       */
      public int getIdentity() {
        return identity_;
      }
      /**
       * <code>required int32 identity = 1;</code>
       *
       * <pre>
       * 用户身份 【0 普通用户 1 客服用户】
       * </pre>
       */
      public Builder setIdentity(int value) {
        bitField0_ |= 0x00000001;
        identity_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 identity = 1;</code>
       *
       * <pre>
       * 用户身份 【0 普通用户 1 客服用户】
       * </pre>
       */
      public Builder clearIdentity() {
        bitField0_ = (bitField0_ & ~0x00000001);
        identity_ = 0;
        onChanged();
        return this;
      }

      // required string deviceId = 2;
      private java.lang.Object deviceId_ = "";
      /**
       * <code>required string deviceId = 2;</code>
       *
       * <pre>
       * 设备唯一标识
       * </pre>
       */
      public boolean hasDeviceId() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string deviceId = 2;</code>
       *
       * <pre>
       * 设备唯一标识
       * </pre>
       */
      public java.lang.String getDeviceId() {
        java.lang.Object ref = deviceId_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          deviceId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string deviceId = 2;</code>
       *
       * <pre>
       * 设备唯一标识
       * </pre>
       */
      public com.google.protobuf.ByteString
          getDeviceIdBytes() {
        java.lang.Object ref = deviceId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          deviceId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string deviceId = 2;</code>
       *
       * <pre>
       * 设备唯一标识
       * </pre>
       */
      public Builder setDeviceId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        deviceId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string deviceId = 2;</code>
       *
       * <pre>
       * 设备唯一标识
       * </pre>
       */
      public Builder clearDeviceId() {
        bitField0_ = (bitField0_ & ~0x00000002);
        deviceId_ = getDefaultInstance().getDeviceId();
        onChanged();
        return this;
      }
      /**
       * <code>required string deviceId = 2;</code>
       *
       * <pre>
       * 设备唯一标识
       * </pre>
       */
      public Builder setDeviceIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        deviceId_ = value;
        onChanged();
        return this;
      }

      // required string token = 3;
      private java.lang.Object token_ = "";
      /**
       * <code>required string token = 3;</code>
       *
       * <pre>
       * 令牌
       * </pre>
       */
      public boolean hasToken() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required string token = 3;</code>
       *
       * <pre>
       * 令牌
       * </pre>
       */
      public java.lang.String getToken() {
        java.lang.Object ref = token_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          token_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string token = 3;</code>
       *
       * <pre>
       * 令牌
       * </pre>
       */
      public com.google.protobuf.ByteString
          getTokenBytes() {
        java.lang.Object ref = token_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          token_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string token = 3;</code>
       *
       * <pre>
       * 令牌
       * </pre>
       */
      public Builder setToken(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        token_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string token = 3;</code>
       *
       * <pre>
       * 令牌
       * </pre>
       */
      public Builder clearToken() {
        bitField0_ = (bitField0_ & ~0x00000004);
        token_ = getDefaultInstance().getToken();
        onChanged();
        return this;
      }
      /**
       * <code>required string token = 3;</code>
       *
       * <pre>
       * 令牌
       * </pre>
       */
      public Builder setTokenBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        token_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:Platform.ModelC10000.C100001c2s)
    }

    static {
      defaultInstance = new C100001c2s(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:Platform.ModelC10000.C100001c2s)
  }

  public interface C100001s2cOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required int32 errCode = 1;
    /**
     * <code>required int32 errCode = 1;</code>
     *
     * <pre>
     * 返回结果 0_成功 1_失败
     * </pre>
     */
    boolean hasErrCode();
    /**
     * <code>required int32 errCode = 1;</code>
     *
     * <pre>
     * 返回结果 0_成功 1_失败
     * </pre>
     */
    int getErrCode();

    // optional string errMsg = 2;
    /**
     * <code>optional string errMsg = 2;</code>
     *
     * <pre>
     * 错误信息 errCode &gt; 0
     * </pre>
     */
    boolean hasErrMsg();
    /**
     * <code>optional string errMsg = 2;</code>
     *
     * <pre>
     * 错误信息 errCode &gt; 0
     * </pre>
     */
    java.lang.String getErrMsg();
    /**
     * <code>optional string errMsg = 2;</code>
     *
     * <pre>
     * 错误信息 errCode &gt; 0
     * </pre>
     */
    com.google.protobuf.ByteString
        getErrMsgBytes();
  }
  /**
   * Protobuf type {@code Platform.ModelC10000.C100001s2c}
   */
  public static final class C100001s2c extends
      com.google.protobuf.GeneratedMessage
      implements C100001s2cOrBuilder {
    // Use C100001s2c.newBuilder() to construct.
    private C100001s2c(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private C100001s2c(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final C100001s2c defaultInstance;
    public static C100001s2c getDefaultInstance() {
      return defaultInstance;
    }

    public C100001s2c getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private C100001s2c(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              errCode_ = input.readInt32();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              errMsg_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.cp.im.proto.c10000msg.C10000.internal_static_Platform_ModelC10000_C100001s2c_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.cp.im.proto.c10000msg.C10000.internal_static_Platform_ModelC10000_C100001s2c_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.cp.im.proto.c10000msg.C10000.C100001s2c.class, com.cp.im.proto.c10000msg.C10000.C100001s2c.Builder.class);
    }

    public static com.google.protobuf.Parser<C100001s2c> PARSER =
        new com.google.protobuf.AbstractParser<C100001s2c>() {
      public C100001s2c parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new C100001s2c(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<C100001s2c> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required int32 errCode = 1;
    public static final int ERRCODE_FIELD_NUMBER = 1;
    private int errCode_;
    /**
     * <code>required int32 errCode = 1;</code>
     *
     * <pre>
     * 返回结果 0_成功 1_失败
     * </pre>
     */
    public boolean hasErrCode() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 errCode = 1;</code>
     *
     * <pre>
     * 返回结果 0_成功 1_失败
     * </pre>
     */
    public int getErrCode() {
      return errCode_;
    }

    // optional string errMsg = 2;
    public static final int ERRMSG_FIELD_NUMBER = 2;
    private java.lang.Object errMsg_;
    /**
     * <code>optional string errMsg = 2;</code>
     *
     * <pre>
     * 错误信息 errCode &gt; 0
     * </pre>
     */
    public boolean hasErrMsg() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional string errMsg = 2;</code>
     *
     * <pre>
     * 错误信息 errCode &gt; 0
     * </pre>
     */
    public java.lang.String getErrMsg() {
      java.lang.Object ref = errMsg_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          errMsg_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string errMsg = 2;</code>
     *
     * <pre>
     * 错误信息 errCode &gt; 0
     * </pre>
     */
    public com.google.protobuf.ByteString
        getErrMsgBytes() {
      java.lang.Object ref = errMsg_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        errMsg_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      errCode_ = 0;
      errMsg_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasErrCode()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, errCode_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getErrMsgBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, errCode_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getErrMsgBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.cp.im.proto.c10000msg.C10000.C100001s2c parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.cp.im.proto.c10000msg.C10000.C100001s2c parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.cp.im.proto.c10000msg.C10000.C100001s2c parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.cp.im.proto.c10000msg.C10000.C100001s2c parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.cp.im.proto.c10000msg.C10000.C100001s2c parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.cp.im.proto.c10000msg.C10000.C100001s2c parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.cp.im.proto.c10000msg.C10000.C100001s2c parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.cp.im.proto.c10000msg.C10000.C100001s2c parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.cp.im.proto.c10000msg.C10000.C100001s2c parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.cp.im.proto.c10000msg.C10000.C100001s2c parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.cp.im.proto.c10000msg.C10000.C100001s2c prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Platform.ModelC10000.C100001s2c}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.cp.im.proto.c10000msg.C10000.C100001s2cOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.cp.im.proto.c10000msg.C10000.internal_static_Platform_ModelC10000_C100001s2c_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.cp.im.proto.c10000msg.C10000.internal_static_Platform_ModelC10000_C100001s2c_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.cp.im.proto.c10000msg.C10000.C100001s2c.class, com.cp.im.proto.c10000msg.C10000.C100001s2c.Builder.class);
      }

      // Construct using com.cp.im.proto.c10000msg.C10000.C100001s2c.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        errCode_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        errMsg_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.cp.im.proto.c10000msg.C10000.internal_static_Platform_ModelC10000_C100001s2c_descriptor;
      }

      public com.cp.im.proto.c10000msg.C10000.C100001s2c getDefaultInstanceForType() {
        return com.cp.im.proto.c10000msg.C10000.C100001s2c.getDefaultInstance();
      }

      public com.cp.im.proto.c10000msg.C10000.C100001s2c build() {
        com.cp.im.proto.c10000msg.C10000.C100001s2c result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.cp.im.proto.c10000msg.C10000.C100001s2c buildPartial() {
        com.cp.im.proto.c10000msg.C10000.C100001s2c result = new com.cp.im.proto.c10000msg.C10000.C100001s2c(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.errCode_ = errCode_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.errMsg_ = errMsg_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.cp.im.proto.c10000msg.C10000.C100001s2c) {
          return mergeFrom((com.cp.im.proto.c10000msg.C10000.C100001s2c)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.cp.im.proto.c10000msg.C10000.C100001s2c other) {
        if (other == com.cp.im.proto.c10000msg.C10000.C100001s2c.getDefaultInstance()) return this;
        if (other.hasErrCode()) {
          setErrCode(other.getErrCode());
        }
        if (other.hasErrMsg()) {
          bitField0_ |= 0x00000002;
          errMsg_ = other.errMsg_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasErrCode()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.cp.im.proto.c10000msg.C10000.C100001s2c parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.cp.im.proto.c10000msg.C10000.C100001s2c) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required int32 errCode = 1;
      private int errCode_ ;
      /**
       * <code>required int32 errCode = 1;</code>
       *
       * <pre>
       * 返回结果 0_成功 1_失败
       * </pre>
       */
      public boolean hasErrCode() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 errCode = 1;</code>
       *
       * <pre>
       * 返回结果 0_成功 1_失败
       * </pre>
       */
      public int getErrCode() {
        return errCode_;
      }
      /**
       * <code>required int32 errCode = 1;</code>
       *
       * <pre>
       * 返回结果 0_成功 1_失败
       * </pre>
       */
      public Builder setErrCode(int value) {
        bitField0_ |= 0x00000001;
        errCode_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 errCode = 1;</code>
       *
       * <pre>
       * 返回结果 0_成功 1_失败
       * </pre>
       */
      public Builder clearErrCode() {
        bitField0_ = (bitField0_ & ~0x00000001);
        errCode_ = 0;
        onChanged();
        return this;
      }

      // optional string errMsg = 2;
      private java.lang.Object errMsg_ = "";
      /**
       * <code>optional string errMsg = 2;</code>
       *
       * <pre>
       * 错误信息 errCode &gt; 0
       * </pre>
       */
      public boolean hasErrMsg() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional string errMsg = 2;</code>
       *
       * <pre>
       * 错误信息 errCode &gt; 0
       * </pre>
       */
      public java.lang.String getErrMsg() {
        java.lang.Object ref = errMsg_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          errMsg_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string errMsg = 2;</code>
       *
       * <pre>
       * 错误信息 errCode &gt; 0
       * </pre>
       */
      public com.google.protobuf.ByteString
          getErrMsgBytes() {
        java.lang.Object ref = errMsg_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          errMsg_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string errMsg = 2;</code>
       *
       * <pre>
       * 错误信息 errCode &gt; 0
       * </pre>
       */
      public Builder setErrMsg(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        errMsg_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string errMsg = 2;</code>
       *
       * <pre>
       * 错误信息 errCode &gt; 0
       * </pre>
       */
      public Builder clearErrMsg() {
        bitField0_ = (bitField0_ & ~0x00000002);
        errMsg_ = getDefaultInstance().getErrMsg();
        onChanged();
        return this;
      }
      /**
       * <code>optional string errMsg = 2;</code>
       *
       * <pre>
       * 错误信息 errCode &gt; 0
       * </pre>
       */
      public Builder setErrMsgBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        errMsg_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:Platform.ModelC10000.C100001s2c)
    }

    static {
      defaultInstance = new C100001s2c(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:Platform.ModelC10000.C100001s2c)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_Platform_ModelC10000_C100001c2s_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Platform_ModelC10000_C100001c2s_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_Platform_ModelC10000_C100001s2c_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Platform_ModelC10000_C100001s2c_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017C10000Msg.proto\022\024Platform.ModelC10000\"" +
      "?\n\nC100001c2s\022\020\n\010identity\030\001 \002(\005\022\020\n\010devic" +
      "eId\030\002 \002(\t\022\r\n\005token\030\003 \002(\t\"-\n\nC100001s2c\022\017" +
      "\n\007errCode\030\001 \002(\005\022\016\n\006errMsg\030\002 \001(\tB#\n\031com.c" +
      "p.im.proto.c10000msgB\006C10000"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_Platform_ModelC10000_C100001c2s_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_Platform_ModelC10000_C100001c2s_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_Platform_ModelC10000_C100001c2s_descriptor,
              new java.lang.String[] { "Identity", "DeviceId", "Token", });
          internal_static_Platform_ModelC10000_C100001s2c_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_Platform_ModelC10000_C100001s2c_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_Platform_ModelC10000_C100001s2c_descriptor,
              new java.lang.String[] { "ErrCode", "ErrMsg", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
