// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: C10001Msg.proto

package com.cp.im.proto.c10001msg;

public final class C10001 {
  private C10001() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface C100011s2cOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required int32 noticeType = 1;
    /**
     * <code>required int32 noticeType = 1;</code>
     *
     * <pre>
     * 通知类型 0_系统 1_个人
     * </pre>
     */
    boolean hasNoticeType();
    /**
     * <code>required int32 noticeType = 1;</code>
     *
     * <pre>
     * 通知类型 0_系统 1_个人
     * </pre>
     */
    int getNoticeType();

    // required string title = 2;
    /**
     * <code>required string title = 2;</code>
     *
     * <pre>
     * 通知标题 
     * </pre>
     */
    boolean hasTitle();
    /**
     * <code>required string title = 2;</code>
     *
     * <pre>
     * 通知标题 
     * </pre>
     */
    java.lang.String getTitle();
    /**
     * <code>required string title = 2;</code>
     *
     * <pre>
     * 通知标题 
     * </pre>
     */
    com.google.protobuf.ByteString
        getTitleBytes();

    // required string content = 3;
    /**
     * <code>required string content = 3;</code>
     *
     * <pre>
     * 通知内容 
     * </pre>
     */
    boolean hasContent();
    /**
     * <code>required string content = 3;</code>
     *
     * <pre>
     * 通知内容 
     * </pre>
     */
    java.lang.String getContent();
    /**
     * <code>required string content = 3;</code>
     *
     * <pre>
     * 通知内容 
     * </pre>
     */
    com.google.protobuf.ByteString
        getContentBytes();
  }
  /**
   * Protobuf type {@code Platform.ModelC10001.C100011s2c}
   *
   * <pre>
   * 软件提醒 1
   * </pre>
   */
  public static final class C100011s2c extends
      com.google.protobuf.GeneratedMessage
      implements C100011s2cOrBuilder {
    // Use C100011s2c.newBuilder() to construct.
    private C100011s2c(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private C100011s2c(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final C100011s2c defaultInstance;
    public static C100011s2c getDefaultInstance() {
      return defaultInstance;
    }

    public C100011s2c getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private C100011s2c(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              noticeType_ = input.readInt32();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              title_ = input.readBytes();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              content_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.cp.im.proto.c10001msg.C10001.internal_static_Platform_ModelC10001_C100011s2c_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.cp.im.proto.c10001msg.C10001.internal_static_Platform_ModelC10001_C100011s2c_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.cp.im.proto.c10001msg.C10001.C100011s2c.class, com.cp.im.proto.c10001msg.C10001.C100011s2c.Builder.class);
    }

    public static com.google.protobuf.Parser<C100011s2c> PARSER =
        new com.google.protobuf.AbstractParser<C100011s2c>() {
      public C100011s2c parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new C100011s2c(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<C100011s2c> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required int32 noticeType = 1;
    public static final int NOTICETYPE_FIELD_NUMBER = 1;
    private int noticeType_;
    /**
     * <code>required int32 noticeType = 1;</code>
     *
     * <pre>
     * 通知类型 0_系统 1_个人
     * </pre>
     */
    public boolean hasNoticeType() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 noticeType = 1;</code>
     *
     * <pre>
     * 通知类型 0_系统 1_个人
     * </pre>
     */
    public int getNoticeType() {
      return noticeType_;
    }

    // required string title = 2;
    public static final int TITLE_FIELD_NUMBER = 2;
    private java.lang.Object title_;
    /**
     * <code>required string title = 2;</code>
     *
     * <pre>
     * 通知标题 
     * </pre>
     */
    public boolean hasTitle() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string title = 2;</code>
     *
     * <pre>
     * 通知标题 
     * </pre>
     */
    public java.lang.String getTitle() {
      java.lang.Object ref = title_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          title_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string title = 2;</code>
     *
     * <pre>
     * 通知标题 
     * </pre>
     */
    public com.google.protobuf.ByteString
        getTitleBytes() {
      java.lang.Object ref = title_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        title_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required string content = 3;
    public static final int CONTENT_FIELD_NUMBER = 3;
    private java.lang.Object content_;
    /**
     * <code>required string content = 3;</code>
     *
     * <pre>
     * 通知内容 
     * </pre>
     */
    public boolean hasContent() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required string content = 3;</code>
     *
     * <pre>
     * 通知内容 
     * </pre>
     */
    public java.lang.String getContent() {
      java.lang.Object ref = content_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          content_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string content = 3;</code>
     *
     * <pre>
     * 通知内容 
     * </pre>
     */
    public com.google.protobuf.ByteString
        getContentBytes() {
      java.lang.Object ref = content_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        content_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      noticeType_ = 0;
      title_ = "";
      content_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasNoticeType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasTitle()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasContent()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, noticeType_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getTitleBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getContentBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, noticeType_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getTitleBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getContentBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.cp.im.proto.c10001msg.C10001.C100011s2c parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.cp.im.proto.c10001msg.C10001.C100011s2c parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.cp.im.proto.c10001msg.C10001.C100011s2c parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.cp.im.proto.c10001msg.C10001.C100011s2c parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.cp.im.proto.c10001msg.C10001.C100011s2c parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.cp.im.proto.c10001msg.C10001.C100011s2c parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.cp.im.proto.c10001msg.C10001.C100011s2c parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.cp.im.proto.c10001msg.C10001.C100011s2c parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.cp.im.proto.c10001msg.C10001.C100011s2c parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.cp.im.proto.c10001msg.C10001.C100011s2c parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.cp.im.proto.c10001msg.C10001.C100011s2c prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Platform.ModelC10001.C100011s2c}
     *
     * <pre>
     * 软件提醒 1
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.cp.im.proto.c10001msg.C10001.C100011s2cOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.cp.im.proto.c10001msg.C10001.internal_static_Platform_ModelC10001_C100011s2c_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.cp.im.proto.c10001msg.C10001.internal_static_Platform_ModelC10001_C100011s2c_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.cp.im.proto.c10001msg.C10001.C100011s2c.class, com.cp.im.proto.c10001msg.C10001.C100011s2c.Builder.class);
      }

      // Construct using com.cp.im.proto.c10001msg.C10001.C100011s2c.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        noticeType_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        title_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        content_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.cp.im.proto.c10001msg.C10001.internal_static_Platform_ModelC10001_C100011s2c_descriptor;
      }

      public com.cp.im.proto.c10001msg.C10001.C100011s2c getDefaultInstanceForType() {
        return com.cp.im.proto.c10001msg.C10001.C100011s2c.getDefaultInstance();
      }

      public com.cp.im.proto.c10001msg.C10001.C100011s2c build() {
        com.cp.im.proto.c10001msg.C10001.C100011s2c result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.cp.im.proto.c10001msg.C10001.C100011s2c buildPartial() {
        com.cp.im.proto.c10001msg.C10001.C100011s2c result = new com.cp.im.proto.c10001msg.C10001.C100011s2c(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.noticeType_ = noticeType_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.title_ = title_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.content_ = content_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.cp.im.proto.c10001msg.C10001.C100011s2c) {
          return mergeFrom((com.cp.im.proto.c10001msg.C10001.C100011s2c)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.cp.im.proto.c10001msg.C10001.C100011s2c other) {
        if (other == com.cp.im.proto.c10001msg.C10001.C100011s2c.getDefaultInstance()) return this;
        if (other.hasNoticeType()) {
          setNoticeType(other.getNoticeType());
        }
        if (other.hasTitle()) {
          bitField0_ |= 0x00000002;
          title_ = other.title_;
          onChanged();
        }
        if (other.hasContent()) {
          bitField0_ |= 0x00000004;
          content_ = other.content_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasNoticeType()) {
          
          return false;
        }
        if (!hasTitle()) {
          
          return false;
        }
        if (!hasContent()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.cp.im.proto.c10001msg.C10001.C100011s2c parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.cp.im.proto.c10001msg.C10001.C100011s2c) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required int32 noticeType = 1;
      private int noticeType_ ;
      /**
       * <code>required int32 noticeType = 1;</code>
       *
       * <pre>
       * 通知类型 0_系统 1_个人
       * </pre>
       */
      public boolean hasNoticeType() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 noticeType = 1;</code>
       *
       * <pre>
       * 通知类型 0_系统 1_个人
       * </pre>
       */
      public int getNoticeType() {
        return noticeType_;
      }
      /**
       * <code>required int32 noticeType = 1;</code>
       *
       * <pre>
       * 通知类型 0_系统 1_个人
       * </pre>
       */
      public Builder setNoticeType(int value) {
        bitField0_ |= 0x00000001;
        noticeType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 noticeType = 1;</code>
       *
       * <pre>
       * 通知类型 0_系统 1_个人
       * </pre>
       */
      public Builder clearNoticeType() {
        bitField0_ = (bitField0_ & ~0x00000001);
        noticeType_ = 0;
        onChanged();
        return this;
      }

      // required string title = 2;
      private java.lang.Object title_ = "";
      /**
       * <code>required string title = 2;</code>
       *
       * <pre>
       * 通知标题 
       * </pre>
       */
      public boolean hasTitle() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string title = 2;</code>
       *
       * <pre>
       * 通知标题 
       * </pre>
       */
      public java.lang.String getTitle() {
        java.lang.Object ref = title_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          title_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string title = 2;</code>
       *
       * <pre>
       * 通知标题 
       * </pre>
       */
      public com.google.protobuf.ByteString
          getTitleBytes() {
        java.lang.Object ref = title_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          title_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string title = 2;</code>
       *
       * <pre>
       * 通知标题 
       * </pre>
       */
      public Builder setTitle(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        title_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string title = 2;</code>
       *
       * <pre>
       * 通知标题 
       * </pre>
       */
      public Builder clearTitle() {
        bitField0_ = (bitField0_ & ~0x00000002);
        title_ = getDefaultInstance().getTitle();
        onChanged();
        return this;
      }
      /**
       * <code>required string title = 2;</code>
       *
       * <pre>
       * 通知标题 
       * </pre>
       */
      public Builder setTitleBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        title_ = value;
        onChanged();
        return this;
      }

      // required string content = 3;
      private java.lang.Object content_ = "";
      /**
       * <code>required string content = 3;</code>
       *
       * <pre>
       * 通知内容 
       * </pre>
       */
      public boolean hasContent() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required string content = 3;</code>
       *
       * <pre>
       * 通知内容 
       * </pre>
       */
      public java.lang.String getContent() {
        java.lang.Object ref = content_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          content_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string content = 3;</code>
       *
       * <pre>
       * 通知内容 
       * </pre>
       */
      public com.google.protobuf.ByteString
          getContentBytes() {
        java.lang.Object ref = content_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          content_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string content = 3;</code>
       *
       * <pre>
       * 通知内容 
       * </pre>
       */
      public Builder setContent(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        content_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string content = 3;</code>
       *
       * <pre>
       * 通知内容 
       * </pre>
       */
      public Builder clearContent() {
        bitField0_ = (bitField0_ & ~0x00000004);
        content_ = getDefaultInstance().getContent();
        onChanged();
        return this;
      }
      /**
       * <code>required string content = 3;</code>
       *
       * <pre>
       * 通知内容 
       * </pre>
       */
      public Builder setContentBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        content_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:Platform.ModelC10001.C100011s2c)
    }

    static {
      defaultInstance = new C100011s2c(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:Platform.ModelC10001.C100011s2c)
  }

  public interface C100012s2cOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required string alias = 1;
    /**
     * <code>required string alias = 1;</code>
     *
     * <pre>
     * 聊天别称
     * </pre>
     */
    boolean hasAlias();
    /**
     * <code>required string alias = 1;</code>
     *
     * <pre>
     * 聊天别称
     * </pre>
     */
    java.lang.String getAlias();
    /**
     * <code>required string alias = 1;</code>
     *
     * <pre>
     * 聊天别称
     * </pre>
     */
    com.google.protobuf.ByteString
        getAliasBytes();

    // repeated string thumbIconURL = 2;
    /**
     * <code>repeated string thumbIconURL = 2;</code>
     *
     * <pre>
     * 聊天图标
     * </pre>
     */
    java.util.List<java.lang.String>
    getThumbIconURLList();
    /**
     * <code>repeated string thumbIconURL = 2;</code>
     *
     * <pre>
     * 聊天图标
     * </pre>
     */
    int getThumbIconURLCount();
    /**
     * <code>repeated string thumbIconURL = 2;</code>
     *
     * <pre>
     * 聊天图标
     * </pre>
     */
    java.lang.String getThumbIconURL(int index);
    /**
     * <code>repeated string thumbIconURL = 2;</code>
     *
     * <pre>
     * 聊天图标
     * </pre>
     */
    com.google.protobuf.ByteString
        getThumbIconURLBytes(int index);

    // required int32 sort = 3;
    /**
     * <code>required int32 sort = 3;</code>
     *
     * <pre>
     * 聊天分类 1_单聊 2_群聊
     * </pre>
     */
    boolean hasSort();
    /**
     * <code>required int32 sort = 3;</code>
     *
     * <pre>
     * 聊天分类 1_单聊 2_群聊
     * </pre>
     */
    int getSort();

    // required int64 attachId = 4;
    /**
     * <code>required int64 attachId = 4;</code>
     *
     * <pre>
     * 附属id = 好友ID/群聊ID
     * </pre>
     */
    boolean hasAttachId();
    /**
     * <code>required int64 attachId = 4;</code>
     *
     * <pre>
     * 附属id = 好友ID/群聊ID
     * </pre>
     */
    long getAttachId();

    // optional string message = 5;
    /**
     * <code>optional string message = 5;</code>
     *
     * <pre>
     * 消息内容
     * </pre>
     */
    boolean hasMessage();
    /**
     * <code>optional string message = 5;</code>
     *
     * <pre>
     * 消息内容
     * </pre>
     */
    java.lang.String getMessage();
    /**
     * <code>optional string message = 5;</code>
     *
     * <pre>
     * 消息内容
     * </pre>
     */
    com.google.protobuf.ByteString
        getMessageBytes();

    // required int32 messageType = 6;
    /**
     * <code>required int32 messageType = 6;</code>
     *
     * <pre>
     * 消息类型 0_文本 1_Emoji 2_图片 3_语音 4_视频
     * </pre>
     */
    boolean hasMessageType();
    /**
     * <code>required int32 messageType = 6;</code>
     *
     * <pre>
     * 消息类型 0_文本 1_Emoji 2_图片 3_语音 4_视频
     * </pre>
     */
    int getMessageType();

    // optional int32 flagTop = 7;
    /**
     * <code>optional int32 flagTop = 7;</code>
     *
     * <pre>
     *标记置顶 0 否 1 是
     * </pre>
     */
    boolean hasFlagTop();
    /**
     * <code>optional int32 flagTop = 7;</code>
     *
     * <pre>
     *标记置顶 0 否 1 是
     * </pre>
     */
    int getFlagTop();

    // optional int32 flagStar = 8;
    /**
     * <code>optional int32 flagStar = 8;</code>
     *
     * <pre>
     *标记加星 0 否 1 是
     * </pre>
     */
    boolean hasFlagStar();
    /**
     * <code>optional int32 flagStar = 8;</code>
     *
     * <pre>
     *标记加星 0 否 1 是
     * </pre>
     */
    int getFlagStar();

    // optional int32 notDisturb = 9;
    /**
     * <code>optional int32 notDisturb = 9;</code>
     *
     * <pre>
     *免打扰 0 关闭 1 开启
     * </pre>
     */
    boolean hasNotDisturb();
    /**
     * <code>optional int32 notDisturb = 9;</code>
     *
     * <pre>
     *免打扰 0 关闭 1 开启
     * </pre>
     */
    int getNotDisturb();

    // optional int32 unreadNum = 10;
    /**
     * <code>optional int32 unreadNum = 10;</code>
     *
     * <pre>
     *未读数量
     * </pre>
     */
    boolean hasUnreadNum();
    /**
     * <code>optional int32 unreadNum = 10;</code>
     *
     * <pre>
     *未读数量
     * </pre>
     */
    int getUnreadNum();

    // optional int64 lastTimestamp = 11;
    /**
     * <code>optional int64 lastTimestamp = 11;</code>
     *
     * <pre>
     *消息时间
     * </pre>
     */
    boolean hasLastTimestamp();
    /**
     * <code>optional int64 lastTimestamp = 11;</code>
     *
     * <pre>
     *消息时间
     * </pre>
     */
    long getLastTimestamp();

    // optional string mobile = 12;
    /**
     * <code>optional string mobile = 12;</code>
     *
     * <pre>
     *手机号
     * </pre>
     */
    boolean hasMobile();
    /**
     * <code>optional string mobile = 12;</code>
     *
     * <pre>
     *手机号
     * </pre>
     */
    java.lang.String getMobile();
    /**
     * <code>optional string mobile = 12;</code>
     *
     * <pre>
     *手机号
     * </pre>
     */
    com.google.protobuf.ByteString
        getMobileBytes();
  }
  /**
   * Protobuf type {@code Platform.ModelC10001.C100012s2c}
   *
   * <pre>
   * 聊天提醒 2
   * </pre>
   */
  public static final class C100012s2c extends
      com.google.protobuf.GeneratedMessage
      implements C100012s2cOrBuilder {
    // Use C100012s2c.newBuilder() to construct.
    private C100012s2c(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private C100012s2c(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final C100012s2c defaultInstance;
    public static C100012s2c getDefaultInstance() {
      return defaultInstance;
    }

    public C100012s2c getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private C100012s2c(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              alias_ = input.readBytes();
              break;
            }
            case 18: {
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                thumbIconURL_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000002;
              }
              thumbIconURL_.add(input.readBytes());
              break;
            }
            case 24: {
              bitField0_ |= 0x00000002;
              sort_ = input.readInt32();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000004;
              attachId_ = input.readInt64();
              break;
            }
            case 42: {
              bitField0_ |= 0x00000008;
              message_ = input.readBytes();
              break;
            }
            case 48: {
              bitField0_ |= 0x00000010;
              messageType_ = input.readInt32();
              break;
            }
            case 56: {
              bitField0_ |= 0x00000020;
              flagTop_ = input.readInt32();
              break;
            }
            case 64: {
              bitField0_ |= 0x00000040;
              flagStar_ = input.readInt32();
              break;
            }
            case 72: {
              bitField0_ |= 0x00000080;
              notDisturb_ = input.readInt32();
              break;
            }
            case 80: {
              bitField0_ |= 0x00000100;
              unreadNum_ = input.readInt32();
              break;
            }
            case 88: {
              bitField0_ |= 0x00000200;
              lastTimestamp_ = input.readInt64();
              break;
            }
            case 98: {
              bitField0_ |= 0x00000400;
              mobile_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
          thumbIconURL_ = new com.google.protobuf.UnmodifiableLazyStringList(thumbIconURL_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.cp.im.proto.c10001msg.C10001.internal_static_Platform_ModelC10001_C100012s2c_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.cp.im.proto.c10001msg.C10001.internal_static_Platform_ModelC10001_C100012s2c_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.cp.im.proto.c10001msg.C10001.C100012s2c.class, com.cp.im.proto.c10001msg.C10001.C100012s2c.Builder.class);
    }

    public static com.google.protobuf.Parser<C100012s2c> PARSER =
        new com.google.protobuf.AbstractParser<C100012s2c>() {
      public C100012s2c parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new C100012s2c(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<C100012s2c> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required string alias = 1;
    public static final int ALIAS_FIELD_NUMBER = 1;
    private java.lang.Object alias_;
    /**
     * <code>required string alias = 1;</code>
     *
     * <pre>
     * 聊天别称
     * </pre>
     */
    public boolean hasAlias() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string alias = 1;</code>
     *
     * <pre>
     * 聊天别称
     * </pre>
     */
    public java.lang.String getAlias() {
      java.lang.Object ref = alias_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          alias_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string alias = 1;</code>
     *
     * <pre>
     * 聊天别称
     * </pre>
     */
    public com.google.protobuf.ByteString
        getAliasBytes() {
      java.lang.Object ref = alias_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        alias_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // repeated string thumbIconURL = 2;
    public static final int THUMBICONURL_FIELD_NUMBER = 2;
    private com.google.protobuf.LazyStringList thumbIconURL_;
    /**
     * <code>repeated string thumbIconURL = 2;</code>
     *
     * <pre>
     * 聊天图标
     * </pre>
     */
    public java.util.List<java.lang.String>
        getThumbIconURLList() {
      return thumbIconURL_;
    }
    /**
     * <code>repeated string thumbIconURL = 2;</code>
     *
     * <pre>
     * 聊天图标
     * </pre>
     */
    public int getThumbIconURLCount() {
      return thumbIconURL_.size();
    }
    /**
     * <code>repeated string thumbIconURL = 2;</code>
     *
     * <pre>
     * 聊天图标
     * </pre>
     */
    public java.lang.String getThumbIconURL(int index) {
      return thumbIconURL_.get(index);
    }
    /**
     * <code>repeated string thumbIconURL = 2;</code>
     *
     * <pre>
     * 聊天图标
     * </pre>
     */
    public com.google.protobuf.ByteString
        getThumbIconURLBytes(int index) {
      return thumbIconURL_.getByteString(index);
    }

    // required int32 sort = 3;
    public static final int SORT_FIELD_NUMBER = 3;
    private int sort_;
    /**
     * <code>required int32 sort = 3;</code>
     *
     * <pre>
     * 聊天分类 1_单聊 2_群聊
     * </pre>
     */
    public boolean hasSort() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required int32 sort = 3;</code>
     *
     * <pre>
     * 聊天分类 1_单聊 2_群聊
     * </pre>
     */
    public int getSort() {
      return sort_;
    }

    // required int64 attachId = 4;
    public static final int ATTACHID_FIELD_NUMBER = 4;
    private long attachId_;
    /**
     * <code>required int64 attachId = 4;</code>
     *
     * <pre>
     * 附属id = 好友ID/群聊ID
     * </pre>
     */
    public boolean hasAttachId() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required int64 attachId = 4;</code>
     *
     * <pre>
     * 附属id = 好友ID/群聊ID
     * </pre>
     */
    public long getAttachId() {
      return attachId_;
    }

    // optional string message = 5;
    public static final int MESSAGE_FIELD_NUMBER = 5;
    private java.lang.Object message_;
    /**
     * <code>optional string message = 5;</code>
     *
     * <pre>
     * 消息内容
     * </pre>
     */
    public boolean hasMessage() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional string message = 5;</code>
     *
     * <pre>
     * 消息内容
     * </pre>
     */
    public java.lang.String getMessage() {
      java.lang.Object ref = message_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          message_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string message = 5;</code>
     *
     * <pre>
     * 消息内容
     * </pre>
     */
    public com.google.protobuf.ByteString
        getMessageBytes() {
      java.lang.Object ref = message_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        message_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required int32 messageType = 6;
    public static final int MESSAGETYPE_FIELD_NUMBER = 6;
    private int messageType_;
    /**
     * <code>required int32 messageType = 6;</code>
     *
     * <pre>
     * 消息类型 0_文本 1_Emoji 2_图片 3_语音 4_视频
     * </pre>
     */
    public boolean hasMessageType() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>required int32 messageType = 6;</code>
     *
     * <pre>
     * 消息类型 0_文本 1_Emoji 2_图片 3_语音 4_视频
     * </pre>
     */
    public int getMessageType() {
      return messageType_;
    }

    // optional int32 flagTop = 7;
    public static final int FLAGTOP_FIELD_NUMBER = 7;
    private int flagTop_;
    /**
     * <code>optional int32 flagTop = 7;</code>
     *
     * <pre>
     *标记置顶 0 否 1 是
     * </pre>
     */
    public boolean hasFlagTop() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>optional int32 flagTop = 7;</code>
     *
     * <pre>
     *标记置顶 0 否 1 是
     * </pre>
     */
    public int getFlagTop() {
      return flagTop_;
    }

    // optional int32 flagStar = 8;
    public static final int FLAGSTAR_FIELD_NUMBER = 8;
    private int flagStar_;
    /**
     * <code>optional int32 flagStar = 8;</code>
     *
     * <pre>
     *标记加星 0 否 1 是
     * </pre>
     */
    public boolean hasFlagStar() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    /**
     * <code>optional int32 flagStar = 8;</code>
     *
     * <pre>
     *标记加星 0 否 1 是
     * </pre>
     */
    public int getFlagStar() {
      return flagStar_;
    }

    // optional int32 notDisturb = 9;
    public static final int NOTDISTURB_FIELD_NUMBER = 9;
    private int notDisturb_;
    /**
     * <code>optional int32 notDisturb = 9;</code>
     *
     * <pre>
     *免打扰 0 关闭 1 开启
     * </pre>
     */
    public boolean hasNotDisturb() {
      return ((bitField0_ & 0x00000080) == 0x00000080);
    }
    /**
     * <code>optional int32 notDisturb = 9;</code>
     *
     * <pre>
     *免打扰 0 关闭 1 开启
     * </pre>
     */
    public int getNotDisturb() {
      return notDisturb_;
    }

    // optional int32 unreadNum = 10;
    public static final int UNREADNUM_FIELD_NUMBER = 10;
    private int unreadNum_;
    /**
     * <code>optional int32 unreadNum = 10;</code>
     *
     * <pre>
     *未读数量
     * </pre>
     */
    public boolean hasUnreadNum() {
      return ((bitField0_ & 0x00000100) == 0x00000100);
    }
    /**
     * <code>optional int32 unreadNum = 10;</code>
     *
     * <pre>
     *未读数量
     * </pre>
     */
    public int getUnreadNum() {
      return unreadNum_;
    }

    // optional int64 lastTimestamp = 11;
    public static final int LASTTIMESTAMP_FIELD_NUMBER = 11;
    private long lastTimestamp_;
    /**
     * <code>optional int64 lastTimestamp = 11;</code>
     *
     * <pre>
     *消息时间
     * </pre>
     */
    public boolean hasLastTimestamp() {
      return ((bitField0_ & 0x00000200) == 0x00000200);
    }
    /**
     * <code>optional int64 lastTimestamp = 11;</code>
     *
     * <pre>
     *消息时间
     * </pre>
     */
    public long getLastTimestamp() {
      return lastTimestamp_;
    }

    // optional string mobile = 12;
    public static final int MOBILE_FIELD_NUMBER = 12;
    private java.lang.Object mobile_;
    /**
     * <code>optional string mobile = 12;</code>
     *
     * <pre>
     *手机号
     * </pre>
     */
    public boolean hasMobile() {
      return ((bitField0_ & 0x00000400) == 0x00000400);
    }
    /**
     * <code>optional string mobile = 12;</code>
     *
     * <pre>
     *手机号
     * </pre>
     */
    public java.lang.String getMobile() {
      java.lang.Object ref = mobile_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          mobile_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string mobile = 12;</code>
     *
     * <pre>
     *手机号
     * </pre>
     */
    public com.google.protobuf.ByteString
        getMobileBytes() {
      java.lang.Object ref = mobile_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        mobile_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      alias_ = "";
      thumbIconURL_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      sort_ = 0;
      attachId_ = 0L;
      message_ = "";
      messageType_ = 0;
      flagTop_ = 0;
      flagStar_ = 0;
      notDisturb_ = 0;
      unreadNum_ = 0;
      lastTimestamp_ = 0L;
      mobile_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasAlias()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasSort()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasAttachId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasMessageType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getAliasBytes());
      }
      for (int i = 0; i < thumbIconURL_.size(); i++) {
        output.writeBytes(2, thumbIconURL_.getByteString(i));
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(3, sort_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt64(4, attachId_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(5, getMessageBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeInt32(6, messageType_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeInt32(7, flagTop_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeInt32(8, flagStar_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        output.writeInt32(9, notDisturb_);
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        output.writeInt32(10, unreadNum_);
      }
      if (((bitField0_ & 0x00000200) == 0x00000200)) {
        output.writeInt64(11, lastTimestamp_);
      }
      if (((bitField0_ & 0x00000400) == 0x00000400)) {
        output.writeBytes(12, getMobileBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getAliasBytes());
      }
      {
        int dataSize = 0;
        for (int i = 0; i < thumbIconURL_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeBytesSizeNoTag(thumbIconURL_.getByteString(i));
        }
        size += dataSize;
        size += 1 * getThumbIconURLList().size();
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, sort_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(4, attachId_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(5, getMessageBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(6, messageType_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(7, flagTop_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(8, flagStar_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(9, notDisturb_);
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(10, unreadNum_);
      }
      if (((bitField0_ & 0x00000200) == 0x00000200)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(11, lastTimestamp_);
      }
      if (((bitField0_ & 0x00000400) == 0x00000400)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(12, getMobileBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.cp.im.proto.c10001msg.C10001.C100012s2c parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.cp.im.proto.c10001msg.C10001.C100012s2c parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.cp.im.proto.c10001msg.C10001.C100012s2c parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.cp.im.proto.c10001msg.C10001.C100012s2c parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.cp.im.proto.c10001msg.C10001.C100012s2c parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.cp.im.proto.c10001msg.C10001.C100012s2c parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.cp.im.proto.c10001msg.C10001.C100012s2c parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.cp.im.proto.c10001msg.C10001.C100012s2c parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.cp.im.proto.c10001msg.C10001.C100012s2c parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.cp.im.proto.c10001msg.C10001.C100012s2c parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.cp.im.proto.c10001msg.C10001.C100012s2c prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Platform.ModelC10001.C100012s2c}
     *
     * <pre>
     * 聊天提醒 2
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.cp.im.proto.c10001msg.C10001.C100012s2cOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.cp.im.proto.c10001msg.C10001.internal_static_Platform_ModelC10001_C100012s2c_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.cp.im.proto.c10001msg.C10001.internal_static_Platform_ModelC10001_C100012s2c_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.cp.im.proto.c10001msg.C10001.C100012s2c.class, com.cp.im.proto.c10001msg.C10001.C100012s2c.Builder.class);
      }

      // Construct using com.cp.im.proto.c10001msg.C10001.C100012s2c.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        alias_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        thumbIconURL_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        sort_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        attachId_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000008);
        message_ = "";
        bitField0_ = (bitField0_ & ~0x00000010);
        messageType_ = 0;
        bitField0_ = (bitField0_ & ~0x00000020);
        flagTop_ = 0;
        bitField0_ = (bitField0_ & ~0x00000040);
        flagStar_ = 0;
        bitField0_ = (bitField0_ & ~0x00000080);
        notDisturb_ = 0;
        bitField0_ = (bitField0_ & ~0x00000100);
        unreadNum_ = 0;
        bitField0_ = (bitField0_ & ~0x00000200);
        lastTimestamp_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000400);
        mobile_ = "";
        bitField0_ = (bitField0_ & ~0x00000800);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.cp.im.proto.c10001msg.C10001.internal_static_Platform_ModelC10001_C100012s2c_descriptor;
      }

      public com.cp.im.proto.c10001msg.C10001.C100012s2c getDefaultInstanceForType() {
        return com.cp.im.proto.c10001msg.C10001.C100012s2c.getDefaultInstance();
      }

      public com.cp.im.proto.c10001msg.C10001.C100012s2c build() {
        com.cp.im.proto.c10001msg.C10001.C100012s2c result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.cp.im.proto.c10001msg.C10001.C100012s2c buildPartial() {
        com.cp.im.proto.c10001msg.C10001.C100012s2c result = new com.cp.im.proto.c10001msg.C10001.C100012s2c(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.alias_ = alias_;
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          thumbIconURL_ = new com.google.protobuf.UnmodifiableLazyStringList(
              thumbIconURL_);
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.thumbIconURL_ = thumbIconURL_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000002;
        }
        result.sort_ = sort_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000004;
        }
        result.attachId_ = attachId_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000008;
        }
        result.message_ = message_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000010;
        }
        result.messageType_ = messageType_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000020;
        }
        result.flagTop_ = flagTop_;
        if (((from_bitField0_ & 0x00000080) == 0x00000080)) {
          to_bitField0_ |= 0x00000040;
        }
        result.flagStar_ = flagStar_;
        if (((from_bitField0_ & 0x00000100) == 0x00000100)) {
          to_bitField0_ |= 0x00000080;
        }
        result.notDisturb_ = notDisturb_;
        if (((from_bitField0_ & 0x00000200) == 0x00000200)) {
          to_bitField0_ |= 0x00000100;
        }
        result.unreadNum_ = unreadNum_;
        if (((from_bitField0_ & 0x00000400) == 0x00000400)) {
          to_bitField0_ |= 0x00000200;
        }
        result.lastTimestamp_ = lastTimestamp_;
        if (((from_bitField0_ & 0x00000800) == 0x00000800)) {
          to_bitField0_ |= 0x00000400;
        }
        result.mobile_ = mobile_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.cp.im.proto.c10001msg.C10001.C100012s2c) {
          return mergeFrom((com.cp.im.proto.c10001msg.C10001.C100012s2c)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.cp.im.proto.c10001msg.C10001.C100012s2c other) {
        if (other == com.cp.im.proto.c10001msg.C10001.C100012s2c.getDefaultInstance()) return this;
        if (other.hasAlias()) {
          bitField0_ |= 0x00000001;
          alias_ = other.alias_;
          onChanged();
        }
        if (!other.thumbIconURL_.isEmpty()) {
          if (thumbIconURL_.isEmpty()) {
            thumbIconURL_ = other.thumbIconURL_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureThumbIconURLIsMutable();
            thumbIconURL_.addAll(other.thumbIconURL_);
          }
          onChanged();
        }
        if (other.hasSort()) {
          setSort(other.getSort());
        }
        if (other.hasAttachId()) {
          setAttachId(other.getAttachId());
        }
        if (other.hasMessage()) {
          bitField0_ |= 0x00000010;
          message_ = other.message_;
          onChanged();
        }
        if (other.hasMessageType()) {
          setMessageType(other.getMessageType());
        }
        if (other.hasFlagTop()) {
          setFlagTop(other.getFlagTop());
        }
        if (other.hasFlagStar()) {
          setFlagStar(other.getFlagStar());
        }
        if (other.hasNotDisturb()) {
          setNotDisturb(other.getNotDisturb());
        }
        if (other.hasUnreadNum()) {
          setUnreadNum(other.getUnreadNum());
        }
        if (other.hasLastTimestamp()) {
          setLastTimestamp(other.getLastTimestamp());
        }
        if (other.hasMobile()) {
          bitField0_ |= 0x00000800;
          mobile_ = other.mobile_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasAlias()) {
          
          return false;
        }
        if (!hasSort()) {
          
          return false;
        }
        if (!hasAttachId()) {
          
          return false;
        }
        if (!hasMessageType()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.cp.im.proto.c10001msg.C10001.C100012s2c parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.cp.im.proto.c10001msg.C10001.C100012s2c) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required string alias = 1;
      private java.lang.Object alias_ = "";
      /**
       * <code>required string alias = 1;</code>
       *
       * <pre>
       * 聊天别称
       * </pre>
       */
      public boolean hasAlias() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string alias = 1;</code>
       *
       * <pre>
       * 聊天别称
       * </pre>
       */
      public java.lang.String getAlias() {
        java.lang.Object ref = alias_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          alias_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string alias = 1;</code>
       *
       * <pre>
       * 聊天别称
       * </pre>
       */
      public com.google.protobuf.ByteString
          getAliasBytes() {
        java.lang.Object ref = alias_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          alias_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string alias = 1;</code>
       *
       * <pre>
       * 聊天别称
       * </pre>
       */
      public Builder setAlias(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        alias_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string alias = 1;</code>
       *
       * <pre>
       * 聊天别称
       * </pre>
       */
      public Builder clearAlias() {
        bitField0_ = (bitField0_ & ~0x00000001);
        alias_ = getDefaultInstance().getAlias();
        onChanged();
        return this;
      }
      /**
       * <code>required string alias = 1;</code>
       *
       * <pre>
       * 聊天别称
       * </pre>
       */
      public Builder setAliasBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        alias_ = value;
        onChanged();
        return this;
      }

      // repeated string thumbIconURL = 2;
      private com.google.protobuf.LazyStringList thumbIconURL_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureThumbIconURLIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          thumbIconURL_ = new com.google.protobuf.LazyStringArrayList(thumbIconURL_);
          bitField0_ |= 0x00000002;
         }
      }
      /**
       * <code>repeated string thumbIconURL = 2;</code>
       *
       * <pre>
       * 聊天图标
       * </pre>
       */
      public java.util.List<java.lang.String>
          getThumbIconURLList() {
        return java.util.Collections.unmodifiableList(thumbIconURL_);
      }
      /**
       * <code>repeated string thumbIconURL = 2;</code>
       *
       * <pre>
       * 聊天图标
       * </pre>
       */
      public int getThumbIconURLCount() {
        return thumbIconURL_.size();
      }
      /**
       * <code>repeated string thumbIconURL = 2;</code>
       *
       * <pre>
       * 聊天图标
       * </pre>
       */
      public java.lang.String getThumbIconURL(int index) {
        return thumbIconURL_.get(index);
      }
      /**
       * <code>repeated string thumbIconURL = 2;</code>
       *
       * <pre>
       * 聊天图标
       * </pre>
       */
      public com.google.protobuf.ByteString
          getThumbIconURLBytes(int index) {
        return thumbIconURL_.getByteString(index);
      }
      /**
       * <code>repeated string thumbIconURL = 2;</code>
       *
       * <pre>
       * 聊天图标
       * </pre>
       */
      public Builder setThumbIconURL(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureThumbIconURLIsMutable();
        thumbIconURL_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string thumbIconURL = 2;</code>
       *
       * <pre>
       * 聊天图标
       * </pre>
       */
      public Builder addThumbIconURL(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureThumbIconURLIsMutable();
        thumbIconURL_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string thumbIconURL = 2;</code>
       *
       * <pre>
       * 聊天图标
       * </pre>
       */
      public Builder addAllThumbIconURL(
          java.lang.Iterable<java.lang.String> values) {
        ensureThumbIconURLIsMutable();
        super.addAll(values, thumbIconURL_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string thumbIconURL = 2;</code>
       *
       * <pre>
       * 聊天图标
       * </pre>
       */
      public Builder clearThumbIconURL() {
        thumbIconURL_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string thumbIconURL = 2;</code>
       *
       * <pre>
       * 聊天图标
       * </pre>
       */
      public Builder addThumbIconURLBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureThumbIconURLIsMutable();
        thumbIconURL_.add(value);
        onChanged();
        return this;
      }

      // required int32 sort = 3;
      private int sort_ ;
      /**
       * <code>required int32 sort = 3;</code>
       *
       * <pre>
       * 聊天分类 1_单聊 2_群聊
       * </pre>
       */
      public boolean hasSort() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required int32 sort = 3;</code>
       *
       * <pre>
       * 聊天分类 1_单聊 2_群聊
       * </pre>
       */
      public int getSort() {
        return sort_;
      }
      /**
       * <code>required int32 sort = 3;</code>
       *
       * <pre>
       * 聊天分类 1_单聊 2_群聊
       * </pre>
       */
      public Builder setSort(int value) {
        bitField0_ |= 0x00000004;
        sort_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 sort = 3;</code>
       *
       * <pre>
       * 聊天分类 1_单聊 2_群聊
       * </pre>
       */
      public Builder clearSort() {
        bitField0_ = (bitField0_ & ~0x00000004);
        sort_ = 0;
        onChanged();
        return this;
      }

      // required int64 attachId = 4;
      private long attachId_ ;
      /**
       * <code>required int64 attachId = 4;</code>
       *
       * <pre>
       * 附属id = 好友ID/群聊ID
       * </pre>
       */
      public boolean hasAttachId() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required int64 attachId = 4;</code>
       *
       * <pre>
       * 附属id = 好友ID/群聊ID
       * </pre>
       */
      public long getAttachId() {
        return attachId_;
      }
      /**
       * <code>required int64 attachId = 4;</code>
       *
       * <pre>
       * 附属id = 好友ID/群聊ID
       * </pre>
       */
      public Builder setAttachId(long value) {
        bitField0_ |= 0x00000008;
        attachId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 attachId = 4;</code>
       *
       * <pre>
       * 附属id = 好友ID/群聊ID
       * </pre>
       */
      public Builder clearAttachId() {
        bitField0_ = (bitField0_ & ~0x00000008);
        attachId_ = 0L;
        onChanged();
        return this;
      }

      // optional string message = 5;
      private java.lang.Object message_ = "";
      /**
       * <code>optional string message = 5;</code>
       *
       * <pre>
       * 消息内容
       * </pre>
       */
      public boolean hasMessage() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional string message = 5;</code>
       *
       * <pre>
       * 消息内容
       * </pre>
       */
      public java.lang.String getMessage() {
        java.lang.Object ref = message_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          message_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string message = 5;</code>
       *
       * <pre>
       * 消息内容
       * </pre>
       */
      public com.google.protobuf.ByteString
          getMessageBytes() {
        java.lang.Object ref = message_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          message_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string message = 5;</code>
       *
       * <pre>
       * 消息内容
       * </pre>
       */
      public Builder setMessage(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        message_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string message = 5;</code>
       *
       * <pre>
       * 消息内容
       * </pre>
       */
      public Builder clearMessage() {
        bitField0_ = (bitField0_ & ~0x00000010);
        message_ = getDefaultInstance().getMessage();
        onChanged();
        return this;
      }
      /**
       * <code>optional string message = 5;</code>
       *
       * <pre>
       * 消息内容
       * </pre>
       */
      public Builder setMessageBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        message_ = value;
        onChanged();
        return this;
      }

      // required int32 messageType = 6;
      private int messageType_ ;
      /**
       * <code>required int32 messageType = 6;</code>
       *
       * <pre>
       * 消息类型 0_文本 1_Emoji 2_图片 3_语音 4_视频
       * </pre>
       */
      public boolean hasMessageType() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>required int32 messageType = 6;</code>
       *
       * <pre>
       * 消息类型 0_文本 1_Emoji 2_图片 3_语音 4_视频
       * </pre>
       */
      public int getMessageType() {
        return messageType_;
      }
      /**
       * <code>required int32 messageType = 6;</code>
       *
       * <pre>
       * 消息类型 0_文本 1_Emoji 2_图片 3_语音 4_视频
       * </pre>
       */
      public Builder setMessageType(int value) {
        bitField0_ |= 0x00000020;
        messageType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 messageType = 6;</code>
       *
       * <pre>
       * 消息类型 0_文本 1_Emoji 2_图片 3_语音 4_视频
       * </pre>
       */
      public Builder clearMessageType() {
        bitField0_ = (bitField0_ & ~0x00000020);
        messageType_ = 0;
        onChanged();
        return this;
      }

      // optional int32 flagTop = 7;
      private int flagTop_ ;
      /**
       * <code>optional int32 flagTop = 7;</code>
       *
       * <pre>
       *标记置顶 0 否 1 是
       * </pre>
       */
      public boolean hasFlagTop() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      /**
       * <code>optional int32 flagTop = 7;</code>
       *
       * <pre>
       *标记置顶 0 否 1 是
       * </pre>
       */
      public int getFlagTop() {
        return flagTop_;
      }
      /**
       * <code>optional int32 flagTop = 7;</code>
       *
       * <pre>
       *标记置顶 0 否 1 是
       * </pre>
       */
      public Builder setFlagTop(int value) {
        bitField0_ |= 0x00000040;
        flagTop_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 flagTop = 7;</code>
       *
       * <pre>
       *标记置顶 0 否 1 是
       * </pre>
       */
      public Builder clearFlagTop() {
        bitField0_ = (bitField0_ & ~0x00000040);
        flagTop_ = 0;
        onChanged();
        return this;
      }

      // optional int32 flagStar = 8;
      private int flagStar_ ;
      /**
       * <code>optional int32 flagStar = 8;</code>
       *
       * <pre>
       *标记加星 0 否 1 是
       * </pre>
       */
      public boolean hasFlagStar() {
        return ((bitField0_ & 0x00000080) == 0x00000080);
      }
      /**
       * <code>optional int32 flagStar = 8;</code>
       *
       * <pre>
       *标记加星 0 否 1 是
       * </pre>
       */
      public int getFlagStar() {
        return flagStar_;
      }
      /**
       * <code>optional int32 flagStar = 8;</code>
       *
       * <pre>
       *标记加星 0 否 1 是
       * </pre>
       */
      public Builder setFlagStar(int value) {
        bitField0_ |= 0x00000080;
        flagStar_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 flagStar = 8;</code>
       *
       * <pre>
       *标记加星 0 否 1 是
       * </pre>
       */
      public Builder clearFlagStar() {
        bitField0_ = (bitField0_ & ~0x00000080);
        flagStar_ = 0;
        onChanged();
        return this;
      }

      // optional int32 notDisturb = 9;
      private int notDisturb_ ;
      /**
       * <code>optional int32 notDisturb = 9;</code>
       *
       * <pre>
       *免打扰 0 关闭 1 开启
       * </pre>
       */
      public boolean hasNotDisturb() {
        return ((bitField0_ & 0x00000100) == 0x00000100);
      }
      /**
       * <code>optional int32 notDisturb = 9;</code>
       *
       * <pre>
       *免打扰 0 关闭 1 开启
       * </pre>
       */
      public int getNotDisturb() {
        return notDisturb_;
      }
      /**
       * <code>optional int32 notDisturb = 9;</code>
       *
       * <pre>
       *免打扰 0 关闭 1 开启
       * </pre>
       */
      public Builder setNotDisturb(int value) {
        bitField0_ |= 0x00000100;
        notDisturb_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 notDisturb = 9;</code>
       *
       * <pre>
       *免打扰 0 关闭 1 开启
       * </pre>
       */
      public Builder clearNotDisturb() {
        bitField0_ = (bitField0_ & ~0x00000100);
        notDisturb_ = 0;
        onChanged();
        return this;
      }

      // optional int32 unreadNum = 10;
      private int unreadNum_ ;
      /**
       * <code>optional int32 unreadNum = 10;</code>
       *
       * <pre>
       *未读数量
       * </pre>
       */
      public boolean hasUnreadNum() {
        return ((bitField0_ & 0x00000200) == 0x00000200);
      }
      /**
       * <code>optional int32 unreadNum = 10;</code>
       *
       * <pre>
       *未读数量
       * </pre>
       */
      public int getUnreadNum() {
        return unreadNum_;
      }
      /**
       * <code>optional int32 unreadNum = 10;</code>
       *
       * <pre>
       *未读数量
       * </pre>
       */
      public Builder setUnreadNum(int value) {
        bitField0_ |= 0x00000200;
        unreadNum_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 unreadNum = 10;</code>
       *
       * <pre>
       *未读数量
       * </pre>
       */
      public Builder clearUnreadNum() {
        bitField0_ = (bitField0_ & ~0x00000200);
        unreadNum_ = 0;
        onChanged();
        return this;
      }

      // optional int64 lastTimestamp = 11;
      private long lastTimestamp_ ;
      /**
       * <code>optional int64 lastTimestamp = 11;</code>
       *
       * <pre>
       *消息时间
       * </pre>
       */
      public boolean hasLastTimestamp() {
        return ((bitField0_ & 0x00000400) == 0x00000400);
      }
      /**
       * <code>optional int64 lastTimestamp = 11;</code>
       *
       * <pre>
       *消息时间
       * </pre>
       */
      public long getLastTimestamp() {
        return lastTimestamp_;
      }
      /**
       * <code>optional int64 lastTimestamp = 11;</code>
       *
       * <pre>
       *消息时间
       * </pre>
       */
      public Builder setLastTimestamp(long value) {
        bitField0_ |= 0x00000400;
        lastTimestamp_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 lastTimestamp = 11;</code>
       *
       * <pre>
       *消息时间
       * </pre>
       */
      public Builder clearLastTimestamp() {
        bitField0_ = (bitField0_ & ~0x00000400);
        lastTimestamp_ = 0L;
        onChanged();
        return this;
      }

      // optional string mobile = 12;
      private java.lang.Object mobile_ = "";
      /**
       * <code>optional string mobile = 12;</code>
       *
       * <pre>
       *手机号
       * </pre>
       */
      public boolean hasMobile() {
        return ((bitField0_ & 0x00000800) == 0x00000800);
      }
      /**
       * <code>optional string mobile = 12;</code>
       *
       * <pre>
       *手机号
       * </pre>
       */
      public java.lang.String getMobile() {
        java.lang.Object ref = mobile_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          mobile_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string mobile = 12;</code>
       *
       * <pre>
       *手机号
       * </pre>
       */
      public com.google.protobuf.ByteString
          getMobileBytes() {
        java.lang.Object ref = mobile_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          mobile_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string mobile = 12;</code>
       *
       * <pre>
       *手机号
       * </pre>
       */
      public Builder setMobile(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000800;
        mobile_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string mobile = 12;</code>
       *
       * <pre>
       *手机号
       * </pre>
       */
      public Builder clearMobile() {
        bitField0_ = (bitField0_ & ~0x00000800);
        mobile_ = getDefaultInstance().getMobile();
        onChanged();
        return this;
      }
      /**
       * <code>optional string mobile = 12;</code>
       *
       * <pre>
       *手机号
       * </pre>
       */
      public Builder setMobileBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000800;
        mobile_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:Platform.ModelC10001.C100012s2c)
    }

    static {
      defaultInstance = new C100012s2c(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:Platform.ModelC10001.C100012s2c)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_Platform_ModelC10001_C100011s2c_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Platform_ModelC10001_C100011s2c_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_Platform_ModelC10001_C100012s2c_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Platform_ModelC10001_C100012s2c_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017C10001Msg.proto\022\024Platform.ModelC10001\"" +
      "@\n\nC100011s2c\022\022\n\nnoticeType\030\001 \002(\005\022\r\n\005tit" +
      "le\030\002 \002(\t\022\017\n\007content\030\003 \002(\t\"\350\001\n\nC100012s2c" +
      "\022\r\n\005alias\030\001 \002(\t\022\024\n\014thumbIconURL\030\002 \003(\t\022\014\n" +
      "\004sort\030\003 \002(\005\022\020\n\010attachId\030\004 \002(\003\022\017\n\007message" +
      "\030\005 \001(\t\022\023\n\013messageType\030\006 \002(\005\022\017\n\007flagTop\030\007" +
      " \001(\005\022\020\n\010flagStar\030\010 \001(\005\022\022\n\nnotDisturb\030\t \001" +
      "(\005\022\021\n\tunreadNum\030\n \001(\005\022\025\n\rlastTimestamp\030\013" +
      " \001(\003\022\016\n\006mobile\030\014 \001(\tB#\n\031com.cp.im.proto." +
      "c10001msgB\006C10001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_Platform_ModelC10001_C100011s2c_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_Platform_ModelC10001_C100011s2c_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_Platform_ModelC10001_C100011s2c_descriptor,
              new java.lang.String[] { "NoticeType", "Title", "Content", });
          internal_static_Platform_ModelC10001_C100012s2c_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_Platform_ModelC10001_C100012s2c_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_Platform_ModelC10001_C100012s2c_descriptor,
              new java.lang.String[] { "Alias", "ThumbIconURL", "Sort", "AttachId", "Message", "MessageType", "FlagTop", "FlagStar", "NotDisturb", "UnreadNum", "LastTimestamp", "Mobile", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
